version: "3.8"

services:
  primary_db:
    image: mysql:latest
    container_name: calendar_system_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=calendar_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
